Neos:
  Flow:
    http:
      middlewares:
        redirect:
          position: 'before routing'
          middleware: 'Wwwision\GraphQL\Http\HttpOptionsMidleware'

Wwwision:
  GraphQL:
    endpoints: []
#      'some-endpoint':
#        'queryType': 'Some\Fully\Qualified\Namespace'
#        'mutationType': 'Some\Fully\Qualified\Namespace'
