Neos:
  Flow:
    http:
      chain:
        'process':
          chain:
            'graphQLOptions':
              position: 'before routing'
              component: 'Wwwision\GraphQL\Http\HttpOptionsComponent'

Wwwision:
  GraphQL:
    endpoints: []
#      'some-endpoint':
#        'queryType': 'Some\Fully\Qualified\Namespace'
#        'mutationType': 'Some\Fully\Qualified\Namespace'
